# # Tuples: ordered ,immutable, allows duplicate elements

# # mytuple = ("Max", 28, "Boston")
# mytyple = ("Max",)
# print(type(mytyple))

# item = my

# jhyau lagyo yo tuple ko kura (generated by git hub copilot)
